const miRopa = [
    {
        id: 1,
        name: 'ZAPATILLAS ADIDAS ULTRABOOST DNA XXII',
        price: 55.999,
        img: './img/hombre/zapatilla_hombre.jpg',
        category: 'hombre',
    },
    {
        id: 2,
        name: 'ZAPATILLAS ADIDAS ORIGINALS NMD_V3',
        price: 47.999,
        img: './img/hombre/zapatilla_hombre2.jpg',
        category: 'hombre',
    },
    {
        id: 3,
        name: 'ZAPATILLAS ADIDAS ORIGINALS ZX 1K BOOST 2.0',
        price: 34.099,
        img: './img/hombre/zapatilla_hombre3.jpg',
        category: 'hombre',
    },
    {
        id: 4,
        name: 'ZAPATILLAS PUMA TRC BLAZE',
        price: 29.999,
        img: './img/hombre/zapatilla_hombre4.jpg',
        category: 'hombre',
    },
    {
        id: 5,
        name: 'ZAPATILLAS NEW BALANCE 574',
        price: 32.599,
        img: './img/hombre/zapatilla_hombre5.jpg',
        category: 'hombre',
    },
    {
        id: 6,
        name: 'ZAPATILLAS NIKE AIR FORCE 1 GTX',
        price: 65.999,
        img: './img/hombre/zapatilla_hombre6.jpg',
        category: 'hombre',
    },
    {
        id: 7,
        name: 'ZAPATILLAS NEW BALANCE 997',
        price: 33.599,
        img: './img/hombre/zapatilla_hombre7.jpg',
        category: 'hombre',
    },
    {
        id: 8,
        name: 'ZAPATILLAS ADIDAS ORIGINALS ZX 1K BOOST 2.0',
        price: 34.099,
        img: './img/hombre/zapatilla_hombre8.jpg',
        category: 'hombre',
    },
    {
        id: 9,
        name: 'CAMPERA PUMA SWXP',
        price: 28.999,
        img: './img/hombre/campera_hombre.jpg',
        category: 'hombre',
    },
    {
        id: 10,
        name: 'CAMPERA ADIDAS ORIGINALS ADICOLOR COLORBLOCK',
        price: 32.999,
        img: './img/hombre/campera_hombre2.jpg',
        category: 'hombre',
    },
    {
        id: 11,
        name: 'BUZO NIKE REVIVAL',
        price: 25.199,
        img: './img/hombre/buzo_hombre.jpg',
        category: 'hombre',
    },
    {
        id: 12,
        name: 'BUZO ADIDAS ORIGINALS GRAPHIC',
        price: 28.599,
        img: './img/hombre/buzo_hombre2.jpg',
        category: 'hombre',
    },
    {
        id: 13,
        name: 'BUZO ADIDAS ORIGINALS MONOGRAMA ESTAMPADO',
        price: 28.999,
        img: './img/hombre/buzo_hombre3.jpg',
        category: 'hombre',
    },
    {
        id: 14,
        name: 'PANTALON ADIDAS ORIGINALS NMD ESSENTILAS',
        price: 25.999,
        img: './img/hombre/pantalon_hombre.jpg',
        category: 'hombre',
    },
    {
        id: 15,
        name: 'PANTALON ADIDAS ORIGINALS ADICOLOR COLORBLOCK',
        price: 28.999,
        img: './img/hombre/pantalon_hombre2.jpg',
        category: 'hombre',
    },
    {
        id: 16,
        name: 'REMERA ADIDAS ORIGINALS VICTORY',
        price: 13.199,
        img: './img/hombre/remera_hombre.jpg',
        category: 'hombre',
    },
    {
        id: 17,
        name: 'REMERA ADIDAS OVERSIZED',
        price: 15.999,
        img: './img/hombre/remera_hombre2.jpg',
        category: 'hombre',
    },
    {
        id: 18,
        name: 'REMERA NIKE MAX 90',
        price: 13.799,
        img: './img/hombre/remera_hombre3.jpg',
        category: 'hombre',
    },
    {
        id: 19,
        name: 'BERMUDA ADIDAS ORIGINALS ESSENTIALS',
        price: 15.399,
        img: './img/hombre/short_hombre.jpg',
        category: 'hombre',
    },
    {
        id: 20,
        name: 'SHORT ADIDAS ORIGINALS 3 STRIPES',
        price: 15.399,
        img: './img/hombre/short_hombre2.jpg',
        category: 'hombre',
    },
    {
        id: 21,
        name: 'ZAPATILLAS PUMA KOSMOS RIDER',
        price: 27.999,
        img: './img/mujer/zapatilla_mujer.jpg',
        category: 'mujer',
    },
    {
        id: 22,
        name: 'ZAPATILLAS PUMA FUTURE RIDER',
        price: 27.999,
        img: './img/mujer/zapatilla_mujer2.jpg',
        category: 'mujer',
    },
    {
        id: 23,
        name: 'ZAPATILLAS ADIDAS ZNTASY',
        price: 31.999,
        img: './img/mujer/zapatilla_mujer3.jpg',
        category: 'mujer',
    },
    {
        id: 24,
        name: 'ZAPATILLAS NEW BALANCE 574',
        price: 30.699,
        img: './img/mujer/zapatilla_mujer4.jpg',
        category: 'mujer',
    },
    {
        id: 25,
        name: 'ZAPATILLAS ADIDAS ORIGINALS NMD R1',
        price: 42.899,
        img: './img/mujer/zapatilla_mujer5.jpg',
        category: 'mujer',
    },
    {
        id: 26,
        name: 'ZAPATILLAS ADIDAS ORIGINALS ASTIR',
        price: 32.999,
        img: './img/mujer/zapatilla_mujer6.jpg',
        category: 'mujer',
    },
    {
        id: 27,
        name: 'ZAPATILLAS NIKE AIR FORCE 1 SHADOW',
        price: 44.399,
        img: './img/mujer/zapatilla_mujer8.jpg',
        category: 'mujer',
    },
    {
        id: 28,
        name: 'CAMPERA PUMA INFUSE',
        price: 28.999,
        img: './img/mujer/campera_mujer.jpg',
        category: 'mujer',
    },
    {
        id: 29,
        name: 'CAMPERA NIKE AIR',
        price: 35.999,
        img: './img/mujer/campera_mujer2.jpg',
        category: 'mujer',
    },
    {
        id: 30,
        name: 'CAMPERA FILA OVERHEAT',
        price: 25.290,
        img: './img/mujer/campera_mujer3.jpg',
        category: 'mujer',
    },
    {
        id: 31,
        name: 'BUZO PUMA POWER COLORBLOCK',
        price: 17.999,
        img: './img/mujer/buzo_mujer.jpg',
        category: 'mujer',
    },
    {
        id: 32,
        name: 'BUZO ADIDAS ORIGINALS DISNEY',
        price: 28.999,
        img: './img/mujer/buzo_mujer2.jpg',
        category: 'mujer',
    },
    {
        id: 33,
        name: 'PANTALON CHAMPION MULTI',
        price: 15.999,
        img: './img/mujer/pantalon_mujer.jpg',
        category: 'mujer',
    },
    {
        id: 34,
        name: 'PANTALON ADIDAS ORIGINALS',
        price: 18.699,
        img: './img/mujer/pantalon_mujer2.jpg',
        category: 'mujer',
    },
    {
        id: 35,
        name: 'CALZAS JORDAN ESSENTIAL',
        price: 18.599,
        img: './img/mujer/calza_mujer.jpg',
        category: 'mujer',
    },
    {
        id: 36,
        name: 'CALZAS NIKE AIR',
        price: 22.199,
        img: './img/mujer/calza_mujer2.jpg',
        category: 'mujer',
    },
    {
        id: 37,
        name: 'REMERA CHAMPION MULTI',
        price: 7.499,
        img: './img/mujer/remera_mujer.jpg',
        category: 'mujer',
    },
    {
        id: 38,
        name: 'REMERA ADIDAS ORIGINALS RICH MNISI',
        price: 11.999,
        img: './img/mujer/remera_mujer2.jpg',
        category: 'mujer',
    },
    {
        id: 39,
        name: 'TOP DEPORTIVO JORDAN JAMPMAN',
        price: 11.999,
        img: './img/mujer/top_mujer.jpg',
        category: 'mujer',
    },
    {
        id: 40,
        name: 'TOP DEPORTIVO NIKE AIR MAX',
        price: 29.399,
        img: './img/mujer/top_mujer2.jpg',
        category: 'mujer',
    },
    {
        id: 41,
        name: 'SHORT ADIDAS',
        price: 14.999,
        img: './img/mujer/short_mujer.jpg',
        category: 'mujer',
    },
    {
        id: 42,
        name: 'POLLERA ADIDAS RICH MNISI',
        price: 19.999,
        img: './img/mujer/short_mujer2.jpg',
        category: 'mujer',
    },
    {
        id: 43,
        name: 'ZAPATILLAS NIKE FORCE 1 TOGGLE',
        price: 29.999,
        img: './img/niños/zapatilla_niños.jpg',
        category: 'niños',
    },
    {
        id: 44,
        name: 'ZAPATILLAS PUMA JADA',
        price: 12.999,
        img: './img/niños/zapatilla_niños2.jpg',
        category: 'niños',
    },
    {
        id: 45,
        name: 'ZAPATILLAS ADIDAS ORIGINALS STAN SMITH',
        price: 19.999,
        img: './img/niños/zapatilla_niños3.jpg',
        category: 'niños',
    },
    {
        id: 46,
        name: 'ZAPATILLAS ADIDAS ORIGINALS SUPERSTAR 360',
        price: 16.999,
        img: './img/niños/zapatilla_niños4.jpg',
        category: 'niños',
    },
    {
        id: 47,
        name: 'ZAPATILLAS PUMA FUTURE RIDER',
        price: 25.999,
        img: './img/niños/zapatilla_niños5.jpg',
        category: 'niños',
    },
    {
        id: 48,
        name: 'ZAPATILLAS ADIDAS ORIGINALS SUPERSTAR 360 CAPITAN AMERICA',
        price: 15.399,
        img: './img/niños/zapatilla_niños6.jpg',
        category: 'niños',
    },
    {
        id: 49,
        name: 'ZAPATILLAS FILA DISRUPTOR VLC',
        price: 14.990,
        img: './img/niños/zapatilla_niños7.jpg',
        category: 'niños',
    },
    {
        id: 50,
        name: 'ZAPATILLAS ADIDAS ORIGINALS SUPERSTAR',
        price: 16.999,
        img: './img/niños/zapatilla_niños8.jpg',
        category: 'niños',
    },
    {
        id: 51,
        name: 'CAMPERA NIKE G NSW CLUB FLC FZ HOODIE LBR',
        price: 14.999,
        img: './img/niños/campera_niños.jpg',
        category: 'niños',
    },
    {
        id: 52,
        name: 'CAMPERA ADIDAS ORIGINALS ADICOLOR',
        price: 30.999,
        img: './img/niños/campera_niños2.jpg',
        category: 'niños',
    },
    {
        id: 53,
        name: 'BUZO NIKE NSW AIR',
        price: 16.799,
        img: './img/niños/buzo_niños.jpg',
        category: 'niños',
    },
    {
        id: 54,
        name: 'BUZO NIKE CLUB',
        price: 14.399,
        img: './img/niños/buzo_niños2.jpg',
        category: 'niños',
    },
    {
        id: 55,
        name: 'BUZO NIKE CLUB',
        price: 14.399,
        img: './img/niños/buzo_niños3.jpg',
        category: 'niños',
    },
    {
        id: 56,
        name: 'BUZO NIKE NSW',
        price: 14.399,
        img: './img/niños/buzo_niños4.jpg',
        category: 'niños',
    },
    {
        id: 57,
        name: 'PANTALON PUMA ESSENTIALS LOGO',
        price: 6.299,
        img: './img/niños/pantalon_niños.jpg',
        category: 'niños',
    },
    {
        id: 58,
        name: 'PANTALON ADIDAS ORIGINALS SST ESTAMPADO',
        price: 13.999,
        img: './img/niños/pantalon_niños2.jpg',
        category: 'niños',
    },
    {
        id: 59,
        name: 'REMERA NIKE FUTURA BOXY',
        price: 7.199,
        img: './img/niños/remera_niños.jpg',
        category: 'niños',
    },
    {
        id: 60,
        name: 'REMERA NIKE NSW ICON CLASH',
        price: 5.639,
        img: './img/niños/remera_niños2.jpg',
        category: 'niños',
    },
    {
        id: 61,
        name: 'REMERA PUMA ESSENTILAS LOGO',
        price: 5.499,
        img: './img/niños/remera_niños3.jpg',
        category: 'niños',
    },
    {
        id: 62,
        name: 'REMERA ADIDAS ORIGINALS DISNEY MICKEY Y AMIGOS',
        price: 8.499,
        img: './img/niños/remera_niños4.jpg',
        category: 'niños',
    },
    {
        id: 63,
        name: 'BUZO TOPPER LONG',
        price: 17.599,
        img: './img/oferta/oferta.jpg',
        category: 'oferta',
    },
    {
        id: 64,
        name: 'GORRA TOPPER BEANIE',
        price: 2.249,
        img: './img/oferta/oferta2.jpg',
        category: 'oferta',
    },
    {
        id: 65,
        name: 'BUZO PUMA SMALL LOGO',
        price: 8.799,
        img: './img/oferta/oferta3.jpg',
        category: 'oferta',
    },
    {
        id: 66,
        name: 'PANTALON ADIDAS ORIGINALS LOGO',
        price: 24.199,
        img: './img/oferta/oferta4.jpg',
        category: 'oferta',
    },
    {
        id: 67,
        name: 'BOLSO ADIDAS ORIGINALS SHOPPER',
        price: 17.599,
        img: './img/oferta/oferta5.jpg',
        category: 'oferta',
    },
    {
        id: 68,
        name: 'PANTALON ADIDAS ORIGINALS LOGO GRANDE',
        price: 24.199,
        img: './img/oferta/oferta6.jpg',
        category: 'oferta',
    },
    {
        id: 69,
        name: 'REMERA ADIDAS ORIGINALS ESTAMPADA',
        price: 10.999,
        img: './img/oferta/oferta7.jpg',
        category: 'oferta',
    },
    {
        id: 70,
        name: 'PANTALON PUMA CRYSTAL',
        price: 15.999,
        img: './img/oferta/oferta8.jpg',
        category: 'oferta',
    },
    {
        id: 71,
        name: 'SHORT ADIDAS ORIGINALS 3 STRIPES',
        price: 10.999,
        img: './img/oferta/oferta9.jpg',
        category: 'oferta',
    },
    {
        id: 72,
        name: 'REMERA ADIDAS ORIGINALS TREFOIL',
        price: 9.399,
        img: './img/oferta/oferta10.jpg',
        category: 'oferta',
    },
    {
        id: 73,
        name: 'ZAPATILLAS ADIDAS ORIGINALS GEODIVER',
        price: 25.299,
        img: './img/oferta/oferta11.jpg',
        category: 'oferta',
    },
    {
        id: 74,
        name: 'ZAPATILLAS ADIDAS ORIGINALS SUPERSTAR',
        price: 28.599,
        img: './img/oferta/oferta12.jpg',
        category: 'oferta',
    },
    {
        id: 75,
        name: 'ZAPATILLAS ADIDAS ORIGINALS MULTIX',
        price: 21.999,
        img: './img/oferta/oferta13.jpg',
        category: 'oferta',
    },
    {
        id: 76,
        name: 'BUZO ADIDAS ORIGINALS ADICOLOR',
        price: 27.499,
        img: './img/oferta/oferta14.jpg',
        category: 'oferta',
    },
    {
        id: 77,
        name: 'REMERA ADIDAS ORIGINALS HER STUDIO LONDON',
        price: 9.399,
        img: './img/oferta/oferta15.jpg',
        category: 'oferta',
    },
    {
        id: 78,
        name: 'CAMPERA ADIDAS ORIGINALS FLORAL',
        price: 27.499,
        img: './img/oferta/oferta16.jpg',
        category: 'oferta',
    },
    {
        id: 79,
        name: 'BUZO ADIDAS ORIGINALS HER STUDIO LONDON',
        price: 23.099,
        img: './img/oferta/oferta17.jpg',
        category: 'oferta',
    },
    {
        id: 80,
        name: 'CAMPERA ADIDAS ORIGINALS ADICOLOR CLASSICS',
        price: 27.499,
        img: './img/oferta/oferta18.jpg',
        category: 'oferta',
    },
    {
        id: 81,
        name: 'VESTIDO ADIDAS ORIGINALS ROSA',
        price: 23.099,
        img: './img/oferta/oferta19.jpg',
        category: 'oferta',
    },
    {
        id: 82,
        name: 'PANTALON PUMA ESSENTIALS LOGO',
        price: 6.299,
        img: './img/oferta/oferta20.jpg',
        category: 'oferta',
    },
    {
        id: 83,
        name: 'ZAPATILLAS ADIDAS NMD_R1',
        price: 42.899,
        img: './img/adidas/adidas.jpg',
        category: 'adidas',
    },
    {
        id: 84,
        name: 'ZAPATILLAS ADIDAS ORIGINALS NMD_R1',
        price: 38.499,
        img: './img/adidas/adidas2.jpg',
        category: 'adidas',
    },
    {
        id: 85,
        name: 'ZAPATILLAS ADIDAS ULTRABOOST DNA XXII',
        price: 55.999,
        img: './img/adidas/adidas3.jpg',
        category: 'adidas',
    },
    {
        id: 86,
        name: 'ZAPATILLAS ADIDAS ORIGINALS OZRAH',
        price: 38.999,
        img: './img/adidas/adidas4.jpg',
        category: 'adidas',
    },
    {
        id: 87,
        name: 'ZAPATILLAS ADIDAS ULTRABOOST DNA XXII',
        price: 55.999,
        img: './img/adidas/adidas5.jpg',
        category: 'adidas',
    },
    {
        id: 88,
        name: 'ZAPATILLAS ADIDAS ORIGINALS NMD_R1',
        price: 41.999,
        img: './img/adidas/adidas6.jpg',
        category: 'adidas',
    },
    {
        id: 89,
        name: 'ZAPATILLAS ADIDAS ORIGINALS FORUM LOW',
        price: 40.699,
        img: './img/adidas/adidas7.jpg',
        category: 'adidas',
    },
    {
        id: 90,
        name: 'ZAPATILLAS ADIDAS ORIGINALS FORUM',
        price: 41.799,
        img: './img/adidas/adidas8.jpg',
        category: 'adidas',
    },
    {
        id: 91,
        name: 'ZAPATILLAS PUMA FUTURE RIDER',
        price: 27.999,
        img: './img/puma/puma.jpg',
        category: 'puma',
    },
    {
        id: 92,
        name: 'ZAPATILLAS PUMA KOSMOS RIDER',
        price: 27.999,
        img: './img/puma/puma2.jpg',
        category: 'puma',
    },
    {
        id: 93,
        name: 'ZAPATILLAS PUMA KOSMOS RIDER',
        price: 27.999,
        img: './img/puma/puma3.jpg',
        category: 'puma',
    },
    {
        id: 94,
        name: 'ZAPATILLAS PUMA SLIPSTREAM RETRO',
        price: 32.999,
        img: './img/puma/puma4.jpg',
        category: 'puma',
    },
    {
        id: 95,
        name: 'ZAPATILLAS PUMA TRC BLAZE',
        price: 29.999,
        img: './img/puma/puma5.jpg',
        category: 'puma',
    },
    {
        id: 96,
        name: 'ZAPATILLAS PUMA CITY RIDER',
        price: 24.999,
        img: './img/puma/puma6.jpg',
        category: 'puma',
    },
    {
        id: 97,
        name: 'ZAPATILLAS PUMA RS FAST LIMITER',
        price: 30.999,
        img: './img/puma/puma7.jpg',
        category: 'puma',
    },
    {
        id: 98,
        name: 'ZAPATILLAS PUMA RIDER FV FUTURE VINTAGE',
        price: 27.999,
        img: './img/puma/puma8.jpg',
        category: 'puma',
    },
]

const splitProducts = (size) => {
    let dividedProducts = [];
    for (let i = 0; i < miRopa.length; i += size)
      dividedProducts.push(miRopa.slice(i, i + size));
    return dividedProducts;
};
  
const productsController = {
    dividedProducts: splitProducts(8),
    nextProductsIndex: 1,
    productsLimit: splitProducts(8).length,
};